name: Ruby Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.3', '3.4']

    steps:
    - uses: actions/checkout@v4 # Checkout the repository code

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # Caches installed gems for faster builds

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rake test
